Add option to run `cml ci`
iterative/setup-cml pull request #71
Opened 2022-05-31 16:03 UTC by 0x2b3bfa0

2022-05-31 23:55 UTC, 0x2b3bfa0 commented
```yaml
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@cml-ci
        with:
          ci: --unshallow --user-name=0x2b3bfa0
        env:
          GITHUB_TOKEN: ${{ github.token }}
```

2022-06-01 09:33 UTC, DavidGOrtega requested changes
Thanks for the effort! 🙏 

Im reluctant to accept the PR yet due to philosophical CML questions that we should debate in our meeting

2022-06-01 11:41 UTC, 0x2b3bfa0 commented
Yes, sure! 🙏🏼 I was asking myself the same questions

2022-06-01 17:12 UTC, casperdcl commented on action.yml
> +    description: Run `cml ci` after installing CML.
```suggestion
    description: Also run `cml ci` (`true`) or flags to forward to `cml ci` (str).
```

I think? i.e. `ci: '--user-email=${{ github.actor }}@users.noreply.github.com'`

2022-06-13 18:52 UTC, 0x2b3bfa0 commented
🔔 @iterative/cml, can you please refresh our collective memory with regard to the outcome of that meeting? 😅

2022-06-13 19:30 UTC, dacbd commented
I believe we agreed that it's a good nice-ity to provide, but not a to-be heavily advertised feature (other than here) since it's GitHub actions-specific feature.

2022-06-13 19:36 UTC, dacbd approved these changes
I'm not a fan of the overloading

2022-06-16 07:11 UTC, casperdcl reviewed
probably needs the "inputs" section of the readme updated too?

2022-10-12 16:17 UTC, 0x2b3bfa0 commented
@iterative/cml, what do we do with this?

2022-10-12 17:03 UTC, dacbd commented
Close and revisit if something like this is requested.

2022-10-12 18:08 UTC, closed without merging

2023-03-09 22:07 UTC, 0x2b3bfa0 commented
See also https://iterativeai.slack.com/archives/C01900GSB4J/p1678389554307949